name: release

on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write
    repository-projects: write

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
            NODE_ENV: production
        steps:
            - uses: actions/checkout@v4

            - name: 检查 EXPO_TOKEN 是否存在
              run: |
                  if [ -z "$EXPO_TOKEN" ]; then
                    echo "EXPO_TOKEN 未设置"
                    exit 1
                  else
                    echo "EXPO_TOKEN 已设置"
                  fi

            - name: 启动java 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 17
                  cache: 'gradle'

            - name: 配置 Android SDK 缓存
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.android
                      ~/.gradle
                      ${{ env.ANDROID_SDK_ROOT || '$HOME/android-sdk' }}
                  key: android-sdk-${{ runner.os }}-${{ hashFiles('**/build.gradle*', '**/settings.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      android-sdk-${{ runner.os }}-

            - name: 安装 Android SDK
              uses: android-actions/setup-android@v3

            - name: 安装 安卓开发工具
              run: |
                  sdkmanager "platforms;android-35" \
                             "build-tools;35.0.0" \
                             "ndk;27.1.12297006"

            - name: 配置 node_modules 缓存
              uses: actions/cache@v4
              with:
                  path: |
                      **/node_modules
                  key: node-modules-${{ runner.os }}-node20-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
                  restore-keys: |
                      node-modules-${{ runner.os }}-node20-

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: 安装 npm 依赖
              run: |
                  npm i -g eas-cli expo expo-doctor expo-cli typescript
                  npm i

            - name: 打包expo应用
              run: |
                  npm run build

            - name: 获取版本号
              id: version
              run: echo "VERSION=$(npm pkg get version | tr -d '\"')" >> $GITHUB_ENV

            - name: 重命名apk
              run: |
                  # 获取第一个 apk 文件名
                  APK_FILE=$(ls *.apk | head -n 1)
                  # 重命名
                  mv "$APK_FILE" "v${{ env.VERSION }}.apk"

            - name: 发布 Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: v${{ env.VERSION }}
                  tag_name: v${{ env.VERSION }}
                  body: |
                      发布版本 v${{ env.VERSION }}
                      - 更新了依赖
                      - 修复了一些问题
                  files: 'v${{ env.VERSION }}.apk'
